# Generated by Django 3.1.2 on 2020-10-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Manga'), ('d', 'DC Comics'), ('mc', 'MARVEL Comics')], default='m', max_length=2),
        ),
    ]
