# Generated by Django 3.1.2 on 2020-10-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201028_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='tipos',
        ),
    ]
